version: '3'
services: 
  nginx:
    image: nginx:latest
    ports: 
      - 8080:80
    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on: 
      - php
  
  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
    depends_on: 
      - db
  
  db: 
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=app-database
      - MYSQL_USER=test
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ='Asia/Tokyo'
    volumes:
      - db-store:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./logs:/var/log/mysql
    ports: 
      - 3307:3306

volumes:
  db-store:
    
